[package]
name = "rbxlx2vmf"
version = "0.1.2"
edition = "2021"
publish = false

[dependencies]
clap = "2.33.3"
roxmltree = "0.14.1"
image = "0.23.14"
reqwest = { version = "0.11.6", features = ["blocking", "json"] }
serde_json = "1.0.71"
flate2 = "1.0.22"