[package]
name = "rbxlx2vmf-web"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wee_alloc = { version = "0.4.5" }
rbxlx2vmf = { path = "../." }

[profile.release]
opt-level = "s"
